[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "proxsuite_nlp"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
examples = [
    "matplotlib",
    "casadi",
    "typed-argument-parser",
    "meshcat @ git+https://github.com/inria-paris-robotic-lab/meshcat-python"
]

[tool.setuptools]
packages = ["proxsuite_nlp"]
package-dir = {"" = "python"}

[tool.ruff]
exclude = [".git", "build*", "cmake"]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501"]
fixable = ["E"]

[tool.ruff.lint.per-file-ignores]
"bindings/python/proxsuite_nlp/__init__.py" = ["F401", "F403"]
